// <auto-generated />
namespace VendaProdutos.Infraestrutura.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SegundaVersao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SegundaVersao));
        
        string IMigrationMetadata.Id
        {
            get { return "201905031628269_SegundaVersao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
